# Use postgres/example user/password credentials
version: '3.9'

# docker-compose up -d
services:

  # psql -h localhost -p 5432 -U postgres
  postgres-li:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  # server: postgres-li
  # user: postgres
  # password: example
  # database: postgres
  adminer-li:
    image: adminer
    restart: always
    ports:
      - 8080:8080
