ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
        watch: # auto-reloading: ./gradlew -t installDist
          - main
    development: true
    environment: $?KTOR_ENV # optional
